# Menu config
# 功能表配置

[[main]]
  identifier = "posts"
  # you can add extra information before the name (HTML format is supported), such as icons
  # 你可以在名稱 (允許 HTML 格式) 之前添加其他資訊, 例如圖示
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  # 你可以在名稱 (允許 HTML 格式) 之後添加其他資訊, 例如圖示
  post = ""
  name = "所有文章"
  url = "/posts/"
  # title will be shown when you hover on this menu link.
  # 將滑鼠懸停在此功能表連結上時將顯示標題。
  title = ""
  weight = 1
[[main]]
  identifier = "tags"
  pre = ""
  post = ""
  name = "標籤"
  url = "/tags/"
  title = ""
  weight = 2
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "分類"
  url = "/categories/"
  title = ""
  weight = 3
[[main]]
  identifier = "series"
  pre = ""
  post = ""
  name = "系列"
  url = "/series/"
  title = ""
  weight = 4
[[main]]
  identifier = "authors"
  pre = ""
  post = ""
  name = "作者"
  url = "/authors/"
  title = ""
  weight = 5
[[main]]
  identifier = "showcase"
  pre = ""
  post = ""
  name = "作品"
  url = "/showcase/"
  title = ""
  weight = 6
[[main]]
  identifier = "documentation"
  pre = ""
  name = "文檔"
  url = "/categories/documentation/"
  title = ""
  weight = 7
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "關於"
  url = "/about/"
  title = ""
  weight = 8
[[main]]
  identifier = "github"
  pre = "<i class='fab fa-github fa-fw'></i>"
  post = ""
  name = ""
  url = "https://github.com/HEIGE-PCloud/DoIt"
  title = "GitHub"
  weight = 9